<?php $this->headTitle($this->translate('Your new password is set')) ?>

<h1><?php echo $this->translate('Your new password is set') ?></h1>

<p>Your password is now reset and you can start logging into your account
using your new password.</p>

<p>Just head over to the <a href="<?php echo $this->url(array (
    'module' => 'account',
    'controller' => 'auth',
    'action' => 'login',
), null, true) ?>" title="login page">login page</a> and get
started again.</p>