<?php $this->headTitle($this->translate('Projects')) ?>

<h1><?php echo $this->translate('Projects') ?></h1>

<?php if (!empty($this->projects)): ?>
<table>
    <tr>
        <th>Project</th>
        <th>Last modified</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->projects as $project): ?>
    <tr>
        <td><?php echo $this->escape($project->getTitle()) ?></td>
        <td><?php echo $this->escape($project->getModified()->format('Y-m-d')) ?></td>
        <td>...</td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>
