<?php $this->headTitle('Your current projects') ?>

<h1>Your current projects</h1>

<?php if (0 === count($this->projectCollection)): ?>
<p>Currently no projects assigned. <a href="<?php echo $this->url(array (
    'module' => 'project',
    'controller' => 'index',
    'action' => 'edit',
    'projectId' => 0,
), null, true) ?>" title="Add a project now">Add a project now</a>.</p>
<?php else: ?>
<table>
    <tr class="tableHeader">
        <th>Project name</th>
        <th>Last modified</th>
        <th><a class="action-add" href="<?php echo $this->url(array (
    'module' => 'project',
    'controller' => 'index',
    'action' => 'edit',
    'projectId' => 0,
), null, true) ?>" title="Add a new project">[ADD]</a></th>
    </tr>
    <?php $rowCount = 0; ?>
    <?php foreach ($this->projectCollection as $project): ?>
    <tr class="tableRow <?php echo (0 === $rowCount % 2 ? 'even' : 'odd') ?>">
        <td><a class="action-edit" href="<?php echo $this->url(array (
            'module' => 'task',
            'controller' => 'index',
            'action' => 'list',
            'projectId' => $project->getId(),
        ), null, true) ?>" title="View tasks for <?php echo $this->escape($project->getProjectName()) ?>"><?php echo $this->escape($project->getProjectName()) ?></a></td>
        <td><?php echo $this->escape($project->getModified()->format('Y-m-d H:i:s')) ?></td>
        <td><a href="<?php echo $this->url(array (
    'module' => 'project',
    'controller' => 'index',
    'action' => 'edit',
    'projectId' => $project->getId(),
), null, true) ?>" title="Edit this project">[EDIT]</a></td>
    </tr>
    <?php $rowCount++ ?>
    <?php endforeach; ?>
</table>
<?php endif; ?>
