
<h1>Watch and learn</h1>
<p class="intro">TheiaLive is a simple task manager, used to serve as an
example application for training and tutorials purposes. You can register
and try out the application but there's no business involved with this
application.</p>
<h1>Run in the cloud</h1>
<p class="intro">We're using the cloud powers of Microsoft's <a 
href="http://www.windowsazure.com" title="Windows Azure">Windows Azure</a> as
it allows us to simply deploy newer versions to the cloud.</p>