<?php $this->headTitle($this->translate('Sign into your account')) ?>

<h1><?php echo $this->translate('Sign into your account') ?></h1>
<p>Here you can sign into your account.</p>
<?php if (!empty ($this->warning)): ?>
<div class="warning"><?php echo $this->escape($this->translate(array_shift($this->warning))) ?></div>
<?php endif; ?>
<?php echo $this->form ?>
<p>No account yet? Register for a 90-day free trial here: 
    <a class="button" href="<?php echo $this->url(array (
        'module' => 'auth',
        'controller' => 'index',
        'action' => 'signup',
    ), null, true) ?>">Register</a></p>