<?php $this->headTitle('Registration successful') ?>

<h1>Registration successful</h1>
<p>Dear <?php echo $this->escape($this->name) ?>,<br/><br/>We have successfully
received your registration request.</p>
<p>To verify your account, we have sent you an email as confirmation to this
    registration. All you need to do is click on the link provided in the email
    to activate your account.</p>
<p>If you have further questions, don't hesitate to <a href="<?php echo $this->url(array (
    'module' => 'default',
    'controller' => 'index',
    'action' => 'contact',
), null, true) ?>" title="Contac us">contact us</a>.</p>
<p>Best regards,<br/><br/>The TheiaLive Team</p>