<div class="navblock"><a href="<?php echo $this->url(array (
    'module' => 'auth', 
    'controller' => 'index', 
    'action' => 'index'
), null, true) ?>"><?php echo $this->translate('login') ?></a></div>

<div class="navblock"><a href="<?php echo $this->url(array (
    'module' => 'auth', 
    'controller' => 'index', 
    'action' => 'signup'
), null, true) ?>"><?php echo $this->translate('sign up') ?></a></div>