<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('TheiaLive'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/styles/main.css')
                        ->appendStylesheet('http://fonts.googleapis.com/css?family=Exo') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js') ?>

    </head>
    <body>
        <div id="master">
            <div id="header">
                <div id="topheader">
                    <div id="logo"><a href="<?php echo $this->url('home') ?>" title="TheiaLive, track your relations"><strong>Theia</strong><i>live</i></a></div>
                    <div id="topnav">
                        <?php //echo $this->accountSettings(); ?>
                    </div>
                </div>
                <div id="midheader"></div>
                <div id="botheader"></div>
            </div>
            <div id="middle" class="">
                <div class="content">

<?php echo $this->content; ?>

                </div>
            </div>
            <div id="footer"></div>
        </div>
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
