  <?php $this->headTitle('An error has occured') ?>
  <?php $this->headMeta('Environment', getenv(APPLICATION_ENV)) ?>
  <h1>An error occurred</h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>
  
  <h3>Platform:</h3>
  <p>
      <b>Server:</b> <?php echo $_SERVER['HTTP_HOST'] ?><br/>
      <b>Environment:</b> <?php echo APPLICATION_ENV ?>
  </p>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre style="overflow: auto; padding: 15px; border: 1px solid black;"><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre style="overflow: auto; padding: 15px; border: 1px solid black;"><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>
